version: '3'

services:
  app:
    image: jamshidbekmansurov/smart-start:latest
    container_name: smart_start_app
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      smart_start_postgres:
        condition: service_healthy
      smart_start_redis:
        condition: service_healthy
    networks:
      - smart_start_network

  smart_start_postgres:
    image: postgres:16-alpine
    container_name: smart_start_postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - smart_start_postgres_data:/var/lib/postgresql/data
    networks:
      - smart_start_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  smart_start_redis:
    image: redis:7.2-alpine
    container_name: smart_start_redis
    ports:
      - '6380:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - smart_start_redis_data:/data
    networks:
      - smart_start_network
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  smart_start_postgres_data:
  smart_start_redis_data:

networks:
  smart_start_network:
    driver: bridge
