name: Deploy NestJS to Ubuntu Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smart-start:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/smart-start:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/smart-start:buildcache,mode=max
      
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Application directory
            mkdir -p ~/smart-start
            cd ~/smart-start
            
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/smart-start:latest
            
            # Stop and remove current container if exists
            if [ -f docker-compose.yml ]; then
              docker-compose down || true
            fi
            
            # Create .env file from GitHub secret
            printf "%s" "${{ secrets.ENV_FILE }}" > .env
            
            # Create or update docker-compose.yml
            cat > docker-compose.yml << 'EOL'
            version: '3'

            services:
              app:
                image: ${{ secrets.DOCKER_USERNAME }}/smart-start:latest
                container_name: smart_start_app
                restart: always
                ports:
                  - '4000:4000'
                env_file:
                  - .env
                depends_on:
                  smart_start_postgres:
                    condition: service_healthy
                  smart_start_redis:
                    condition: service_healthy
                networks:
                  - smart_start_network

              smart_start_postgres:
                image: postgres:16-alpine
                container_name: smart_start_postgres
                ports:
                  - '5433:5432'
                environment:
                  - POSTGRES_USER=${DB_USERNAME}
                  - POSTGRES_PASSWORD=${DB_PASSWORD}
                  - POSTGRES_DB=${DB_NAME}
                volumes:
                  - smart_start_postgres_data:/var/lib/postgresql/data
                networks:
                  - smart_start_network
                healthcheck:
                  test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
                  interval: 10s
                  timeout: 5s
                  retries: 5

              smart_start_redis:
                image: redis:7.2-alpine
                container_name: smart_start_redis
                ports:
                  - '6380:6379'
                command: redis-server --requirepass ${REDIS_PASSWORD}
                volumes:
                  - smart_start_redis_data:/data
                networks:
                  - smart_start_network
                healthcheck:
                  test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
                  interval: 10s
                  timeout: 5s
                  retries: 5

            volumes:
              smart_start_postgres_data:
              smart_start_redis_data:

            networks:
              smart_start_network:
                driver: bridge
            EOL
            
            # Start the application
            docker-compose up -d --force-recreate --no-deps
            
            # Prune unused images to save disk space
            docker image prune -a -f --filter "until=24h"
            
            # Check if application started successfully
            sleep 15
            docker ps --filter "name=smart_start_app"
            docker-compose logs --tail=30 app