name: Deploy NestJS to Ubuntu Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smart-start:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/smart-start:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/smart-start:buildcache,mode=max
      
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Application directory
            mkdir -p ~/smart-start
            cd ~/smart-start
            
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/smart-start:latest
            
            # Stop and remove current container if exists
            docker-compose down || true
            
            # Create .env file from GitHub secret
            echo "${{ secrets.ENV_FILE }}" > .env
            
            # Create or update docker-compose.yml
            cat > docker-compose.yml << 'EOL'
            version: '3'
            
            services:
              app:
                image: ${{ secrets.DOCKER_USERNAME }}/smart-start:latest
                restart: always
                ports:
                  - '4000:4000'
                env_file:
                  - .env
                depends_on:
                  postgres:
                    condition: service_healthy
                  redis:
                    condition: service_healthy
                networks:
                  - nestjs-network
            
              postgres:
                image: postgres:16-alpine
                ports:
                  - '5433:5432'
                environment:
                  - POSTGRES_USER=${DB_USERNAME}
                  - POSTGRES_PASSWORD=${DB_PASSWORD}
                  - POSTGRES_DB=${DB_NAME}
                volumes:
                  - postgres_data:/var/lib/postgresql/data
                networks:
                  - nestjs-network
                healthcheck:
                  test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
                  interval: 10s
                  timeout: 5s
                  retries: 5
            
              redis:
                image: redis:7.2-alpine
                ports:
                  - '6380:6379'
                command: redis-server --requirepass ${REDIS_PASSWORD}
                volumes:
                  - redis_data:/data
                networks:
                  - nestjs-network
                healthcheck:
                  test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
                  interval: 10s
                  timeout: 5s
                  retries: 5
            
            volumes:
              postgres_data:
              redis_data:
            
            networks:
              nestjs-network:
                driver: bridge
            EOL
            
            # Start the application
            docker-compose up -d
            
            # Prune unused images to save disk space
            docker image prune -a -f --filter "until=24h"
            
            # Check if application started successfully
            sleep 15
            docker-compose ps
            docker-compose logs --tail=30 app